### ISSUE TITLE
Handling JSON Schema $refs

### ISSUE THREAD

**Issue by devonsparks** [disneystreaming/smithy-translate#191] opened 2023-09-15 23:02 UTC
How best to handle JSON Schema $refs when using `json-schema-to-smithy`? We have some existing JSON Schema definitions that use relative path references. Attemping `json-schema-to-smithy` on them results in `java.io.UncheckedIOException: java.net.MalformedURLException: no protocol`. If I place the same collection of JSON Schema definitions behind a local web service, and update all $refs to be absolute HTTP URLs, I instead get a `java.net.ConnectException: Connection refused` error, even though the URLs are accessible on the machine. Is there any convention for (or otherwise a way to direct) `smithytranslate` to resolve $refs?

**Comment by Baccata** [comment] 2023-09-18 07:32
Can you share a minimal example of something that doesn't work ?

**Comment by Baccata** [comment] 2023-12-08 11:57
Closing because of lack of reply from original poster. 

Feel free to re-open if you find the time to provide a minimal reproduction.

**Closed by Baccata** 2023-12-08 11:57 UTC
